export default [{
    "poster_path": "/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg",
    "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    "release_date": "1994-09-10",
    "id": 278,
    "title": "The Shawshank Redemption",
    "backdrop_path": "/xBKGJQsAIeweesB79KC89FpBrVr.jpg",
    "popularity": 7.911657,
    "vote_count": 5448,
    "vote_average": 8.33,
    "genres": ["Drama", "Crime"]
}, {
    "poster_path": "/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg",
    "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    "release_date": "2014-10-10",
    "id": 244786,
    "title": "Whiplash",
    "backdrop_path": "/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg",
    "popularity": 9.727756,
    "vote_count": 2170,
    "vote_average": 8.26,
    "genres": ["Drama", "Music"]
}, {
    "poster_path": "/d4KNaTrltq6bpkFS01pYtyXa09m.jpg",
    "overview": "The story spans the years from 1945 to 1955 and chronicles the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    "release_date": "1972-03-15",
    "id": 238,
    "title": "The Godfather",
    "backdrop_path": "/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg",
    "popularity": 6.088924,
    "vote_count": 3740,
    "vote_average": 8.25,
    "genres": ["Drama", "Crime"]
}, {
    "poster_path": "/s0C78plmx3dFcO3WMnoXCz56FiN.jpg",
    "overview": "A boy growing up in Dublin during the 1980s escapes his strained family life by starting a band to impress the mysterious girl he likes.",
    "release_date": "2016-04-15",
    "id": 369557,
    "title": "Sing Street",
    "backdrop_path": "/9j4UaRypr19wz0BOofwvkPRm1Se.jpg",
    "popularity": 3.194985,
    "vote_count": 107,
    "vote_average": 8.11,
    "genres": ["Romance", "Drama", "Music"]
}, {
    "poster_path": "/tHbMIIF51rguMNSastqoQwR0sBs.jpg",
    "overview": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "release_date": "1974-12-20",
    "id": 240,
    "title": "The Godfather: Part II",
    "backdrop_path": "/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg",
    "popularity": 4.458898,
    "vote_count": 1978,
    "vote_average": 8.1,
    "genres": ["Drama", "Crime"]
}, {
    "poster_path": "/yPisjyLweCl1tbgwgtzBCNCBle.jpg",
    "overview": "Told from the perspective of businessman Oskar Schindler who saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory. Schindler’s List is based on a true story, illustrated in black and white and controversially filmed in many original locations.",
    "release_date": "1993-11-29",
    "id": 424,
    "title": "Schindler's List",
    "backdrop_path": "/rIpSszng8P0DL0TimSzZbpfnvh1.jpg",
    "popularity": 4.700765,
    "vote_count": 2441,
    "vote_average": 8.09,
    "genres": ["Drama", "History", "War"]
}, {
    "poster_path": "/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg",
    "overview": "Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    "release_date": "2014-11-05",
    "id": 157336,
    "title": "Interstellar",
    "backdrop_path": "/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    "popularity": 16.374365,
    "vote_count": 5934,
    "vote_average": 8.09,
    "genres": ["Adventure", "Drama", "Science Fiction"]
}, {
    "poster_path": "/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg",
    "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    "release_date": "2008-07-16",
    "id": 155,
    "title": "The Dark Knight",
    "backdrop_path": "/nnMC0BM6XbjIIrT4miYmMtPGcQV.jpg",
    "popularity": 7.91234,
    "vote_count": 8016,
    "vote_average": 8.07,
    "genres": ["Drama", "Action", "Crime", "Thriller"]
}, {
    "poster_path": "/811DjJTon9gD6hZ8nCjSitaIXFQ.jpg",
    "overview": "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
    "release_date": "1999-10-14",
    "id": 550,
    "title": "Fight Club",
    "backdrop_path": "/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg",
    "popularity": 6.688062,
    "vote_count": 5472,
    "vote_average": 8.07,
    "genres": ["Drama"]
}, {
    "poster_path": "/eqFckcHuFCT1FrzLOAvXBb4jHwq.jpg",
    "overview": "Jack is a young boy of 5 years old who has lived all his life in one room. He believes everything within it are the only real things in the world. But what will happen when his Ma suddenly tells him that there are other things outside of Room?",
    "release_date": "2015-10-16",
    "id": 264644,
    "title": "Room",
    "backdrop_path": "/tBhp8MGaiL3BXpPCSl5xY397sGH.jpg",
    "popularity": 5.909467,
    "vote_count": 1318,
    "vote_average": 8.04,
    "genres": ["Drama", "Thriller"]
}, {
    "poster_path": "/dM2w364MScsjFf8pfMbaWUcWrR.jpg",
    "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    "release_date": "1994-10-14",
    "id": 680,
    "title": "Pulp Fiction",
    "backdrop_path": "/mte63qJaVnoxkkXbHkdFujBnBgd.jpg",
    "popularity": 6.50409,
    "vote_count": 4947,
    "vote_average": 8.04,
    "genres": ["Thriller", "Crime"]
}, {
    "poster_path": "/z4ROnCrL77ZMzT0MsNXY5j25wS2.jpg",
    "overview": "A man with a low IQ has accomplished great things in his life and been present during significant historic events - in each case, far exceeding what anyone imagined he could do. Yet, despite all the things he has attained, his one true love eludes him. 'Forrest Gump' is the story of a man who rose above his challenges, and who proved that determination, courage, and love are more important than ability.",
    "release_date": "1994-07-06",
    "id": 13,
    "title": "Forrest Gump",
    "backdrop_path": "/ctOEhQiFIHWkiaYp7b0ibSTe5IL.jpg",
    "popularity": 6.089368,
    "vote_count": 4486,
    "vote_average": 8.03,
    "genres": ["Comedy", "Drama", "Romance"]
}, {
    "poster_path": "/6u1fYtxG5eqjhtCPDx04pJphQRW.jpg",
    "overview": "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
    "release_date": "1980-01-01",
    "id": 1891,
    "title": "The Empire Strikes Back",
    "backdrop_path": "/AkE7LQs2hPMG5tpWYcum847Knre.jpg",
    "popularity": 4.149377,
    "vote_count": 3696,
    "vote_average": 8.01,
    "genres": ["Adventure", "Action", "Science Fiction"]
}, {
    "poster_path": "/2Sns5oMb356JNdBHgBETjIpRYy9.jpg",
    "overview": "While serving time for insanity at a state mental hospital, implacable rabble-rouser Randle Patrick McMurphy inspires his fellow patients to rebel against the authoritarian rule of head nurse Mildred Ratched.",
    "release_date": "1975-11-18",
    "id": 510,
    "title": "One Flew Over the Cuckoo's Nest",
    "backdrop_path": "/8qpUbdLQJHPnTi0DgnBGHZJokSz.jpg",
    "popularity": 4.565453,
    "vote_count": 1461,
    "vote_average": 8.01,
    "genres": ["Drama"]
}, {
    "poster_path": "/pwpGfTImTGifEGgLb3s6LRPd4I6.jpg",
    "overview": "Henry Hill is a small time gangster, who takes part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who have set their sights a bit higher. His two partners kill off everyone else involved in the robbery, and slowly start to climb up through the hierarchy of the Mob. Henry, however, is badly affected by his partners success, but will he stoop low enough to bring about the downfall of Jimmy and Tommy?",
    "release_date": "1990-09-12",
    "id": 769,
    "title": "Goodfellas",
    "backdrop_path": "/xDEOxA01480uLTWuvQCw61VmDBt.jpg",
    "popularity": 3.646943,
    "vote_count": 1638,
    "vote_average": 8.01,
    "genres": ["Drama", "Crime"]
}, {
    "poster_path": "/qcL1YfkCxfhsdO6sDDJ0PpzMF9n.jpg",
    "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    "release_date": "1957-03-25",
    "id": 389,
    "title": "12 Angry Men",
    "backdrop_path": "/lH2Ga8OzjU1XlxJ73shOlPx6cRw.jpg",
    "popularity": 3.983452,
    "vote_count": 1186,
    "vote_average": 8.01,
    "genres": ["Drama"]
}, {
    "poster_path": "/aAmfIX3TT40zUHGcCKrlOZRKC7u.jpg",
    "overview": "Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Like all of us, Riley is guided by her emotions - Joy, Fear, Anger, Disgust and Sadness. The emotions live in Headquarters, the control center inside Riley's mind, where they help advise her through everyday life. As Riley and her emotions struggle to adjust to a new life in San Francisco, turmoil ensues in Headquarters. Although Joy, Riley's main and most important emotion, tries to keep things positive, the emotions conflict on how best to navigate a new city, house and school.",
    "release_date": "2015-06-09",
    "id": 150540,
    "title": "Inside Out",
    "backdrop_path": "/szytSpLAyBh3ULei3x663mAv5ZT.jpg",
    "popularity": 6.127099,
    "vote_count": 3613,
    "vote_average": 8.01,
    "genres": ["Comedy", "Animation", "Family"]
}, {
    "poster_path": "/lQy2QVcacuH55k37K9Ox0gw3YpZ.jpg",
    "overview": "In 2013, something terrible is awakening in London's National Gallery; in 1562, a murderous plot is afoot in Elizabethan England; and somewhere in space an ancient battle reaches its devastating conclusion. All of reality is at stake as the Doctor's own dangerous past comes back to haunt him.",
    "release_date": "2013-11-23",
    "id": 313106,
    "title": "Doctor Who: The Day of the Doctor",
    "backdrop_path": "/8bxjRFqFztBoXdVEx6q2u66a0s1.jpg",
    "popularity": 1.740327,
    "vote_count": 177,
    "vote_average": 8,
    "genres": ["Science Fiction", "Adventure"]
}, {
    "poster_path": "/tpoaLlY0ZdVGDLToVwkGdWxLHRe.jpg",
    "overview": "A peculiar neighbor offers hope to a recent widow who is struggling to raise a teenager who is unpredictable and, sometimes, violent.",
    "release_date": "2014-05-22",
    "id": 265177,
    "title": "Mommy",
    "backdrop_path": "/ztBezkk2jDQMutGHIa57xvPc2OU.jpg",
    "popularity": 3.050317,
    "vote_count": 349,
    "vote_average": 8,
    "genres": ["Drama"]
}, {
    "poster_path": "/yRXTVpDRBA3983C3HjoY0SO4dV6.jpg",
    "overview": "Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war. As an elite rifle company parachuting into Normandy early on D-Day morning, participants in the Battle of the Bulge, and witness to the horrors of war, the men of Easy knew extraordinary bravery and extraordinary fear - and became the stuff of legend. Based on Stephen E. Ambrose's acclaimed book of the same name.",
    "release_date": "2001-09-09",
    "id": 331214,
    "title": "Band of Brothers",
    "backdrop_path": "/x4cycTgAtBIy4TP0DBD2RhtKpol.jpg",
    "popularity": 1.950538,
    "vote_count": 271,
    "vote_average": 8,
    "genres": ["Action", "Drama", "War"]
}, {
    "poster_path": "/3yJUlOtVa09CYJocwBU8eAryja0.jpg",
    "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cellblock's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    "release_date": "1999-12-10",
    "id": 497,
    "title": "The Green Mile",
    "backdrop_path": "/dATygzDbQGJWlolx2vebgqFYAKO.jpg",
    "popularity": 4.374789,
    "vote_count": 2116,
    "vote_average": 7.99,
    "genres": ["Fantasy", "Drama", "Crime"]
}, {
    "poster_path": "/tkQ1NGAARD6NYEDOVYzal6zfIpo.jpg",
    "overview": "Ricky is a defiant young city kid who finds himself on the run with his cantankerous foster uncle in the wild New Zealand bush. A national manhunt ensues, and the two are forced to put aside their differences and work together to survive.",
    "release_date": "2016-03-31",
    "id": 371645,
    "title": "Hunt for the Wilderpeople",
    "backdrop_path": "/xS35Qsjvpzyiz7wBftfq45PTKOK.jpg",
    "popularity": 2.975321,
    "vote_count": 100,
    "vote_average": 7.99,
    "genres": ["Drama", "Adventure", "Comedy"]
}, {
    "poster_path": "/3TpMBcAYH4cxCw5WoRacWodMTCG.jpg",
    "overview": "An urban office worker finds that paper airplanes are instrumental in meeting a girl in ways he never expected.",
    "release_date": "2012-11-02",
    "id": 140420,
    "title": "Paperman",
    "backdrop_path": "/cqn1ynw78Wan37jzs1Ckm7va97G.jpg",
    "popularity": 2.407347,
    "vote_count": 472,
    "vote_average": 7.98,
    "genres": ["Animation", "Family", "Romance"]
}, {
    "poster_path": "/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg",
    "overview": "Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.",
    "release_date": "2014-11-14",
    "id": 205596,
    "title": "The Imitation Game",
    "backdrop_path": "/qcb6z1HpokTOKdjqDTsnjJk0Xvg.jpg",
    "popularity": 8.952466,
    "vote_count": 3163,
    "vote_average": 7.97,
    "genres": ["History", "Drama", "Thriller", "War"]
}, {
    "poster_path": "/fXepRAYOx1qC3wju7XdDGx60775.jpg",
    "overview": "Derek Vineyard is paroled after serving 3 years in prison for killing two thugs who tried to break into/steal his truck. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
    "release_date": "1998-10-30",
    "id": 73,
    "title": "American History X",
    "backdrop_path": "/i9A0UMFg1hI2kLyCCwnmSbpT2cd.jpg",
    "popularity": 4.011038,
    "vote_count": 1435,
    "vote_average": 7.96,
    "genres": ["Drama"]
}]